Functions Todo
AbbasSarwar/ToDo pull request #3
Opened 2023-03-29 19:34 UTC by AbbasSarwar

### Features
* Addition function
* Removal function
* Editable function
* Indexing Objects in Array
* Select color changes

2023-03-29 20:14 UTC, vickymarz requested changes
Hi @AbbasSarwar , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 


## Required Changes ♻️

- [ ]  I think it will be better if you don't disable any linters for your project because linters enable you to write a bug-free and clean code. So I will encourage you to always fix your linter errors instead of disabling them.

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 20:14 UTC, victorokoroji commented on src/index.js
> +    // eslint-disable-next-line no-restricted-globals
- [ ] I think it will be better if you don't disable any linters for your project because linters enable you to write a bug-free and clean code. So I will encourage you to always fix your linter errors instead of disabling them.

2023-03-29 20:14 UTC, vickymarz commented on src/modules/funtions.js
> +    index: Tasks.length,
- [ ] Good job so far. Kindly note that the project requirement expects that the index of the todos should start from one (1) such that when a fifth todo is added, its index gives 5. please  update your index to start from 1

![image](https://user-images.githubusercontent.com/63473584/228654749-587ca110-e732-4f21-9172-31863674341e.png)

2023-03-29 20:14 UTC, vickymarz commented on src/modules/funtions.js
> +};
- [ ] Your delete functionality is currently working. KIndly check that you are linking the remove event listener to the right element 👍🏽

2023-03-30 07:00 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @AbbasSarwar  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ correct GitHub Flow
✔ The PR title and description are professional and descriptive ✅
✔ Made suggested changes 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 19:19 UTC, closed without merging